mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - dns.msftncsi.com
    - "*.srv.nintendo.net"
    - "*.stun.playstation.net"
    - xbox.*.microsoft.com
    - "*.xboxlive.com"


proxies:



latencytest: &cloudflare {enable: true, url: http://cp.cloudflare.com/generate_204, interval: 600}
proxy-providers:

  Server:
    type: http
    url: 
    path: ./nodelist/Server.yaml
    interval: 86400
    health-check: *cloudflare


type:
  fallback: &fallback {type: fallback, interval: 600, url: http://cp.cloudflare.com/generate_204}
  urltest: &urltest {type: url-test, interval: 600, url: http://cp.cloudflare.com/generate_204}
proxy-groups:
  - name: Proxy
    type: select
    use: [Server]
 




rules:
  - MATCH,Proxy

