mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - dns.msftncsi.com
    - "*.srv.nintendo.net"
    - "*.stun.playstation.net"
    - xbox.*.microsoft.com
    - "*.xboxlive.com"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4
  fallback-filter:
    geoip: true
    geoip-code: CN

proxies:
  - { name: 'xxxxx', type: xxx, server: x.x.x.x, port: xxxx, udp: true, tfo: true, , tls: true, network: tcp: xxxxxx }


latencytest: &cloudflare {enable: true, url: http://cp.cloudflare.com/generate_204, interval: 600}
proxy-providers:
  Nexitally:
    type: http
    url: xxxxxxx
    path: ./nodelist/Nexitally.yaml
    interval: 86400
    health-check: *cloudflare
    # filter: ^((?!Premium).)*$ # Meta only

  TAG:
    type: http
    url: xxxxxx
    path: ./nodelist/TAG.yaml
    interval: 86400
    health-check: *cloudflare

type:
  fallback: &fallback {type: fallback, interval: 600, url: http://cp.cloudflare.com/generate_204}
  urltest: &urltest {type: url-test, interval: 600, url: http://cp.cloudflare.com/generate_204}
proxy-groups:
  - name: Proxy
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan]
    use: [Nexitally, TAG]

    
  - name: YouTube
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]

  - name: OpenAI
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]

  - name: Apple
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]
    
  - name: Google
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]
    
  - name: Netflix
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]
    
  - name: Disney
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]
    
  - name: Steam
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]
    
  - name: Telegram
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]
    
  - name: Speedtest
    type: select
    proxies: [Hong Kong, United States, Singapore, Japan, Taiwan,Proxy,DIRECT]
    
  - name: Hong Kong
    type: select
    use: [Nexitally, TAG]
    filter: Hong Kong|HK|香港
   
  - name: United States
    type: select
    use: [Nexitally, TAG]
    filter: United States|US|美国
    
  - name: Singapore
    type: select
    use: [Nexitally, TAG]
    filter: Singapore|SG|新加坡
   
  - name: Japan
    type: select
    use: [Nexitally, TAG]
    filter: Japan|JP|日本
    
  - name: Taiwan
    type: select
    use: [Nexitally, TAG]
    filter: Taiwan|TW|台湾

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  
  
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,BlockHttpDNS,REJECT
  - DOMAIN-SUFFIX,sentry.io,REJECT
  - RULE-SET,DMM,Japan
  - RULE-SET,Niconico,Japan
  - RULE-SET,YouTube,YouTube
  - RULE-SET,WeChat,DIRECT
  - RULE-SET,Google,Google
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney
  - RULE-SET,Steam,Steam
  - RULE-SET,Telegram,Telegram

  - RULE-SET,icloud,Apple
  - RULE-SET,apple,Apple
  - RULE-SET,proxy,Proxy
  - RULE-SET,direct,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,lancidr,DIRECT
  - IP-CIDR,2.2.2.2/32,DIRECT
  - DOMAIN,www.189.cn,DIRECT
  - MATCH,Proxy

classical: &classical {type: http, behavior: classical, interval: 86400}
domain: &domain {type: http, behavior: domain, interval: 86400}
ipcidr: &ipcidr {type: http, behavior: ipcidr, interval: 86400}
rule-providers:
  Mail:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Mail/Mail_No_Resolve.yaml
    path: ./ruleset/Mail.yaml
  BlockHttpDNS:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS_No_Resolve.yaml
    path: ./ruleset/BlockHttpDNS.yaml
  Niconico:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico_No_Resolve.yaml
    path: ./ruleset/Niconico.yaml
  DMM:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM_No_Resolve.yaml
    path: ./ruleset/DMM.yaml
  YouTube:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube_No_Resolve.yaml
    path: ./ruleset/YouTube.yaml
  GameDownload:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload_No_Resolve.yaml
    path: ./ruleset/GameDownload.yaml
  WeChat:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat_No_Resolve.yaml
    path: ./ruleset/WeChat.yaml
  Riot:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Riot/Riot_No_Resolve.yaml
    path: ./ruleset/Riot.yaml
  Google:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google_No_Resolve.yaml
    path: ./ruleset/Google.yaml
  OpenAI:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml
    path: ./ruleset/OpenAI.yaml
    
  Netflix:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_No_Resolve.yaml
    path: ./ruleset/Netflix.yaml
    
  Disney:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney_No_Resolve.yaml
    path: ./ruleset/Disney.yaml
  Speedtest:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest_No_Resolve.yaml
    path: ./ruleset/Speedtest.yaml
    
  Telegram:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml
    path: ./ruleset/Telegram.yaml
 
  Gooogle:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google_No_Resolve.yaml
    path: ./ruleset/Google.yaml
    
  Steam:
    <<: *classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam_No_Resolve.yaml
    path: ./ruleset/Steam.yaml
    
    
    
    
    
  icloud:
    <<: *domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
    path: ./ruleset/icloud.yaml
  apple:
    <<: *domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
    path: ./ruleset/apple.yaml
  reject:
    <<: *domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    path: ./ruleset/reject.yaml
  proxy:
    <<: *domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./ruleset/proxy.yaml
  direct:
    <<: *domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./ruleset/direct.yaml
  private:
    <<: *domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./ruleset/private.yaml
  telegramcidr:
    <<: *ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
  cncidr:
    <<: *ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    path: ./ruleset/cncidr.yaml
  lancidr:
    <<: *ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
    path: ./ruleset/lancidr.yaml
  applications:
    <<: *classical
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    path: ./ruleset/applications.yaml
